### ISSUE TITLE
Please don't pump minor version with breaking changes.

### ISSUE THREAD

**Issue by leptonyu** [ssrlive/rust-tun#49]
Newest minor change cause code compile error, because method signature is changed.

Please follow semantic version conversions.
https://doc.rust-lang.org/cargo/reference/semver.html

**Comment by ssrlive** [comment]
Well, yanked the older versions.

**Comment by M0dEx** [comment]
I agree and was planning on making an issue as well. These changes should either be made in a backwards-compatible way, with a deprecation warning (with a minor version bump), or the major version should be bumped.

I propose to make the last change (`tun_name`) backwards compatible, which should not be difficult, and add a deprecation warning.

**Comment by M0dEx** [comment]
> Well, yanked the older versions.

This does not help since breaking changes are only expected in new _major_ versions, not in new _minor_ versions, which is a behaviour that Cargo and many users rely on.

A version spec such as `^1.0.0` is still going to upgrade to the `1.1.2` version, which causes the `1.1.2` version to break the "contract" of semver.

**Comment by ssrlive** [comment]
I know, just i'm lazy.

**Comment by ssrlive** [comment]
Thanks for warning.
> A version spec such as ^1.0.0 is still going to upgrade to the 1.1.2 version, breaking the "contract" of semver.

**Comment by xmh0511** [comment]
Since `name` may easily have multiple candidates listed by IDE prompt when coding, for a better coding experience, the `name` is replaced by `tun_name`, which also has a better semantic. However, in terms of the "contract" of `semver`, we just cannot casually remove `name`, so, marking `name` as a deprecated API is a trade-off scheme.
